/**
 * RoomPuzzle — the load-bearing abstraction of the Manor pivot (ARCHITECTURE §2).
 *
 * FROZEN CONTRACT (architect-owned). Agents implement adapters against this
 * interface; they do not edit this file. Change requests go to the architect.
 *
 * Two halves — a pure adapter (engine) and a view (React) — joined by the
 * kind-keyed registries (`engine/rooms/registry.ts` + `ui/rooms/registry.ts`).
 * Adapters never touch steps or the store; they emit events, the room slice
 * applies economy.
 */

export type RoomPuzzleKind =
  | 'word-web' | 'hive' | 'twistle' | 'forgotten-word'  // anchors
  | 'cipher' | 'crossword'                              // micro ("fewer but better")
  | 'sudoku';                                           // playtest round: the Counting House

/** All kinds, in registry order (anchors then micro, alphabetical per batch). */
export const ROOM_PUZZLE_KINDS: readonly RoomPuzzleKind[] = [
  'forgotten-word', 'hive', 'twistle', 'word-web',
  'cipher',
  'crossword',
  'sudoku',
];

export interface RoomContext { tier: 1 | 2 | 3; seed: number; volumeId: string; }

export interface RoomOutcome {
  status: 'active' | 'solved' | 'abandoned';
  /** No costed mistakes AND no purchased hints → +2 bonus (v1 parity). */
  perfect: boolean;
}

export type RoomEvent =                    // consumed by slices, never by adapters
  // weight 0 = free feedback moment (shake/toast, no step cost) — e.g. Conservatory
  // invalid dictionary words per AAA R.1. weight 1|2 = costed, mapped via STEP_TABLE.
  // weight 'structural' = pre-warned structural slip (AAA R.1): flat −1, all tiers.
  | { type: 'mistake'; weight: 0 | 1 | 2 | 'structural' }
  // A3 REVISION (special authority, documented in A3's report): a step-priced
  // hint/clue purchase — the Study's clue unseals and the Library's intruder
  // nudges (AAA 2.10) are bought with steps, the single currency. Maps through
  // the SAME STEP_TABLE row as `mistake` weights (weight 1 → −2, tier 3 −3);
  // a purchased hint also forfeits `perfect`. Never weight 0.
  | { type: 'hint'; weight: 1 | 2 }
  | { type: 'progress'; detail?: string }  // sfx/juice/music-director hook
  | { type: 'solved'; perfect: boolean }
  /**
   * A payout from inside the puzzle. `gems`/`keys` are live (the Conservatory
   * pays a gem at Every Petal).
   *
   * `fragmentId` is a DOCUMENTED SEAM, NOT the room→mystery channel, and the
   * distinction is load-bearing enough to write down (round 9 decision):
   *
   *   - No adapter emits it today. The channel that actually pays the mystery
   *     for solving a word game is the spine watcher in app/slices/journal.ts,
   *     which reads `room-solved` off the audited event stream and calls
   *     `collectFragmentForSolve(kind)` — the Study pays a definition line,
   *     other rooms a lintel engraving, one per channel per day.
   *   - It is KEPT rather than deleted because it is the only way an adapter
   *     could ever hand out ONE SPECIFIC fragment for one specific puzzle (a
   *     future authored set-piece), and app/slices/room.ts already honours it.
   *
   * THE RULE, for whoever writes that adapter: an adapter that emits
   * `fragmentId` is choosing a fragment ITSELF, so the day's channel valve
   * must be closed for that solve or the player is paid twice for one puzzle
   * with two different fragments. Do not wire both.
   */
  | { type: 'reward'; gems?: number; keys?: number; fragmentId?: string };

export interface RoomPuzzleAdapter<P = unknown, S = unknown, A = unknown> {
  kind: RoomPuzzleKind;
  size: 'micro' | 'anchor';
  select(opts: { tier: 1 | 2 | 3; seed: number; seenIds: string[] }): P;   // seeded, seen-aware
  start(puzzle: P, ctx: RoomContext): S;
  reduce(puzzle: P, state: S, action: A): { state: S; events: RoomEvent[]; outcome: RoomOutcome };
  puzzleId(puzzle: P): string;
}
