/**
 * RoomPuzzle — the load-bearing abstraction of the Manor pivot (ARCHITECTURE §2).
 *
 * FROZEN CONTRACT (architect-owned). Agents implement adapters against this
 * interface; they do not edit this file. Change requests go to the architect.
 *
 * Two halves — a pure adapter (engine) and a view (React) — joined by the
 * kind-keyed registries (`engine/rooms/registry.ts` + `ui/rooms/registry.ts`).
 * Adapters never touch steps or the store; they emit events, the room slice
 * applies economy.
 */

export type RoomPuzzleKind =
  | 'word-web' | 'hive' | 'twistle' | 'forgotten-word'                    // anchors
  | 'anagram' | 'ladder' | 'cipher' | 'crossword' | 'rhyme' | 'category'; // micro

/** All kinds, in registry order (anchors then micro, alphabetical per batch). */
export const ROOM_PUZZLE_KINDS: readonly RoomPuzzleKind[] = [
  'forgotten-word', 'hive', 'twistle', 'word-web',
  'anagram', 'cipher', 'ladder',
  'category', 'crossword', 'rhyme',
];

export interface RoomContext { tier: 1 | 2 | 3; seed: number; volumeId: string; }

export interface RoomOutcome {
  status: 'active' | 'solved' | 'abandoned';
  /** No costed mistakes AND no purchased hints → +2 bonus (v1 parity). */
  perfect: boolean;
}

export type RoomEvent =                    // consumed by slices, never by adapters
  // weight 0 = free feedback moment (shake/toast, no step cost) — e.g. Conservatory
  // invalid dictionary words per AAA R.1. weight 1|2 = costed, mapped via STEP_TABLE.
  // weight 'structural' = pre-warned structural slip (AAA R.1): flat −1, all tiers.
  | { type: 'mistake'; weight: 0 | 1 | 2 | 'structural' }
  // A3 REVISION (special authority, documented in A3's report): a step-priced
  // hint/clue purchase — the Study's clue unseals and the Library's intruder
  // nudges (AAA 2.10) are bought with steps, the single currency. Maps through
  // the SAME STEP_TABLE row as `mistake` weights (weight 1 → −2, tier 3 −3);
  // a purchased hint also forfeits `perfect`. Never weight 0.
  | { type: 'hint'; weight: 1 | 2 }
  | { type: 'progress'; detail?: string }  // sfx/juice/music-director hook
  | { type: 'solved'; perfect: boolean }
  | { type: 'reward'; gems?: number; keys?: number; fragmentId?: string };

export interface RoomPuzzleAdapter<P = unknown, S = unknown, A = unknown> {
  kind: RoomPuzzleKind;
  size: 'micro' | 'anchor';
  select(opts: { tier: 1 | 2 | 3; seed: number; seenIds: string[] }): P;   // seeded, seen-aware
  start(puzzle: P, ctx: RoomContext): S;
  reduce(puzzle: P, state: S, action: A): { state: S; events: RoomEvent[]; outcome: RoomOutcome };
  puzzleId(puzzle: P): string;
}
